import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
  about: React.ReactNode;
  dashboard: React.ReactNode;
  detail: React.ReactNode;
}

export default function RootLayout({
  children,
  about,
  dashboard,
  detail,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <main className="flex-grow flex flex-col">
          <Header />
          {children}

          <section>{about}</section>
          <section>{dashboard}</section>
          <section>{detail}</section>
        </main>
      </body>
    </html>
  );
}
